name: Ebiz
description: Ebiz.
version: 1.0.0+1
environment:
  sdk: ">=2.2.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.2
  fluttertoast: any
  sqflite: ^1.1.7+2
  path_provider: ^1.4.0
  google_maps_flutter: ^0.5.21+8
  flutter_staggered_grid_view: ^0.3.0
  flutter_datetime_picker: ^1.2.8
  dio: ^2.2.2
  draggable_scrollbar: ^0.0.4
  intl: ^0.16.0
  connectivity: ^0.4.4
  provider: ^3.1.0+1
  location: ^2.3.5
  progress_dialog: ^1.2.0
  flutter_speed_dial: ^1.2.4
  expandable: ^3.0.1
  firebase_messaging: ^6.0.1
  flutter_local_notifications: ^0.7.1+1
  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.4

flutter_icons:
  image_path: "assets/images/ebiz.png"
  image_path_android : "assets/images/ebiz.png"
  image_path_ios: "assets/images/ebiz.png"
  android: "launcher_icon"
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/ebiz.png
    - assets/images/as.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
